stages:
  - documentation
  - build
  - test
  - quality

build-game:
   stage: build
   script:
      - make cardGame
   
build-tests:
   stage: build
   script:
      - make testGame
   artifacts:
      paths:
         - testGame

coverage:
   stage: test
   script:
      - make coverage
   artifacts:
      paths:
         - coverage
      expire_in: 14 days

memcheckTest:
   stage: quality
   script:
      - make memcheck

staticAnalysis:
   stage: quality
   script:
      - make static

style:
   stage: quality
   script:
      - make style

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days
